cc_library(
    name = "day_01",
    srcs = [
        "day_01.cc",
        "day_01.h",
    ],
    data = [
        "//data:day_01",
    ],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "day_01_bin",
    srcs = [
        "day_01.cc",
        "day_01.h",
    ],
    data = [
        "//data:day_01",
    ],
    visibility = ["//visibility:public"],
)
