cc_library(
    name = "day_01",
    srcs = [
        "day_01.cc",
        "day_01.h",
    ],
    data = [
        "//data:day_01",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "day_02",
    srcs = [
        "day_02.cc",
        "day_02.h",
    ],
    data = [
        "//data:day_02",
    ],
    visibility = ["//visibility:public"],
)
