cc_library(
    name = "day_01",
    srcs = [
        "day_01.cc",
        "day_01.h",
    ],
    data = [
        "//data:day_01",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "day_02",
    srcs = [
        "day_02.cc",
        "day_02.h",
    ],
    data = [
        "//data:day_02",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "day_03",
    srcs = [
        "day_03.cc",
        "day_03.h",
    ],
    data = [
        "//data:day_03",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "day_04",
    srcs = [
        "day_04.cc",
        "day_04.h",
    ],
    data = [
        "//data:day_04",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "day_05",
    srcs = [
        "day_05.cc",
        "day_05.h",
    ],
    data = [
        "//data:day_05",
    ],
    visibility = ["//visibility:public"],
)
