filegroup(
    name = "day_01",
    srcs = [
        "01.txt",
        "01-test.txt",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "day_02",
    srcs = [
        "02.txt",
        "02-test.txt",
    ],
    visibility = ["//visibility:public"],
)
