filegroup(
    name = "day_01",
    srcs = [
        "01.txt",
        "01-test.txt",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "day_02",
    srcs = [
        "02.txt",
        "02-test.txt",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "day_03",
    srcs = [
        "03.txt",
        "03-test.txt",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "day_04",
    srcs = [
        "04.txt",
        "04-test.txt",
    ],
    visibility = ["//visibility:public"],
)
