filegroup(
    name = "day_01",
    srcs = [
        "01.txt",
        "01-test.txt",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "day_02",
    srcs = [
        "02.txt",
        "02-test.txt",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "day_03",
    srcs = [
        "03.txt",
        "03-test.txt",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "day_04",
    srcs = [
        "04.txt",
        "04-test.txt",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "day_05",
    srcs = [
        "05.txt",
        "05-test.txt",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "day_06",
    srcs = [
        "06.txt",
        "06-test.txt",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "day_07",
    srcs = [
        "07.txt",
        "07-test.txt",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "day_08",
    srcs = [
        "08.txt",
        "08-test.txt",
    ],
    visibility = ["//visibility:public"],
)
