cc_test(
    name = "test_day_01",
    srcs = ["test_day_01.cc"],
    deps = [
        "//src/cpp:day_01",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
        "@spdlog",
    ],
)
